### ISSUE TITLE
Aumentar arquivos de palavras 

### ISSUE THREAD

**Issue by filhodanuvem** [BrPedro-dev/Forca#2]
Não sei se você usa linux ou mac. No terminal eu fiz `cat /usr/share/dict/words` e vi que por padrao o sistema operacional já vem com um dicionário de palavras. Tentei procurar esse arquivo para portugues do brasil e caí nesse link, de repente podemos usá-lo para aumentar o arquivo de palavras. Um lado negativo é que não teria só substantivos, você acha isso um problema? 

https://packages.debian.org/pt-br/sid/wbrazilian

**Comment by BrPedro-dev** [comment]
Olá Cloudson, desculpa a demora para responder. Então meu sistema operacional é windows porém estou pensado em migrar para linux. O arquivo que estava me referindo é esse daqui: https://github.com/BrPedro-dev/Forca/blob/master/palavras.txt
Porém você pode mudar nome do arquivo ou até mesmo mudar diretório, porém você terá que mudar na função "rand_word():" que se encontra linha 129. Você deve mudar nessa parte aqui:

**`with open("palavras.txt", "rt") as f:`**
 linha 130("palavras.txt" é nome do arquivo caso quera colocar outro nome você deve modificar o nome do arquivo lembrado de colocar diretório) esse link exemplifica a minha explicação: https://www.alura.com.br/artigos/trabalhando-com-arquivos-e-diretorios-no-python

Como eu disse você pode adicionar qualquer tipo de palavra como adjetivo, substantivos e etc.

Obrigado pelo feedback, tenha um Bom Domingo. E quaisquer dúvida, estamos ai.

**Comment by filhodanuvem** [comment]
Fechando essa issue por enquanto.
